# Generated by Django 5.2.16 on 2026-08-07 03:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vocabulary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        max_length=16,
                    ),
                ),
                ("new_word_target", models.PositiveSmallIntegerField()),
                ("planned_new_word_count", models.PositiveSmallIntegerField()),
                ("item_count", models.PositiveSmallIntegerField()),
                ("planner_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_sessions",
                        to="vocabulary.corpusversion",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StudySessionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("due", "Due review"), ("new", "New Word")],
                        max_length=8,
                    ),
                ),
                ("due_at_snapshot", models.DateTimeField(blank=True, null=True)),
                ("scheduler_version", models.CharField(blank=True, max_length=64)),
                ("scheduling_state_snapshot", models.JSONField(default=dict)),
                ("presented_at", models.DateTimeField(blank=True, null=True)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corpus_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_items",
                        to="vocabulary.corpusentry",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="study.studysession",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="RecallAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("remembered", "Remembered"), ("forgot", "Forgot")],
                        max_length=16,
                    ),
                ),
                ("client_request_id", models.UUIDField(unique=True)),
                ("submitted_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="study.studysessionitem",
                    ),
                ),
            ],
            options={
                "ordering": ("accepted_at",),
            },
        ),
        migrations.CreateModel(
            name="LearnerWordState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("review", "Review"),
                            ("relearning", "Relearning"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "difficulty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "stability",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("review_count", models.PositiveIntegerField()),
                ("lapse_count", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField()),
                ("next_due_at", models.DateTimeField()),
                ("scheduler_version", models.CharField(max_length=64)),
                ("scheduler_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learner_states",
                        to="vocabulary.vocabularyword",
                    ),
                ),
            ],
            options={
                "ordering": ("next_due_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["learner", "next_due_at"],
                        name="study_state_learner_due_idx",
                    ),
                    models.Index(
                        fields=["learner", "phase"],
                        name="study_state_learner_phase_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner", "word"),
                        name="study_unique_learner_word_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("review_count__gte", 1)),
                        name="study_word_state_review_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lapse_count__lte", models.F("review_count"))
                        ),
                        name="study_word_state_lapses_not_above_reviews",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("next_due_at__gt", models.F("last_reviewed_at"))
                        ),
                        name="study_word_state_due_after_review",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scheduler_version", ""), _negated=True),
                        name="study_word_state_scheduler_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("phase__in", ["learning", "review", "relearning"])
                        ),
                        name="study_word_state_phase_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("difficulty__isnull", True),
                            ("difficulty__gt", 0),
                            _connector="OR",
                        ),
                        name="study_word_state_difficulty_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stability__isnull", True),
                            ("stability__gt", 0),
                            _connector="OR",
                        ),
                        name="study_word_state_stability_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("review_number", models.PositiveIntegerField()),
                ("scheduler_version", models.CharField(max_length=64)),
                (
                    "previous_phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("learning", "Learning"),
                            ("review", "Review"),
                            ("relearning", "Relearning"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "next_phase",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("review", "Review"),
                            ("relearning", "Relearning"),
                        ],
                        max_length=16,
                    ),
                ),
                ("previous_due_at", models.DateTimeField(blank=True, null=True)),
                ("next_due_at", models.DateTimeField()),
                ("previous_state", models.JSONField(default=dict)),
                ("next_state", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="study.recallanswer",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["occurred_at"], name="study_outcome_occurred_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("review_number__gte", 1)),
                        name="study_outcome_review_number_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scheduler_version", ""), _negated=True),
                        name="study_outcome_scheduler_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("previous_phase", ""),
                            (
                                "previous_phase__in",
                                ["learning", "review", "relearning"],
                            ),
                            _connector="OR",
                        ),
                        name="study_outcome_previous_phase_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("next_phase__in", ["learning", "review", "relearning"])
                        ),
                        name="study_outcome_next_phase_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("previous_phase", ""),
                                ("previous_due_at__isnull", True),
                            ),
                            models.Q(
                                models.Q(("previous_phase", ""), _negated=True),
                                ("previous_due_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="study_outcome_previous_state_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_state", {}), _negated=True),
                        name="study_outcome_next_state_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("next_due_at__gt", models.F("occurred_at"))
                        ),
                        name="study_outcome_next_due_after_occurrence",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["learner", "status", "-created_at"],
                name="study_session_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("learner",),
                name="study_one_active_session_per_learner",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_new_word_count__lte", models.F("new_word_target"))
                ),
                name="study_session_new_count_within_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_count__gte", models.F("planned_new_word_count")),
                    ("item_count__gte", 1),
                ),
                name="study_session_item_count_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.CheckConstraint(
                condition=models.Q(("planner_version", ""), _negated=True),
                name="study_session_planner_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), ("ended_at__isnull", True)),
                    models.Q(
                        ("status__in", ("completed", "abandoned")),
                        ("ended_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="study_session_status_end_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionitem",
            constraint=models.UniqueConstraint(
                fields=("session", "position"),
                name="study_unique_session_item_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionitem",
            constraint=models.UniqueConstraint(
                fields=("session", "corpus_entry"),
                name="study_unique_session_corpus_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="study_session_item_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "due"),
                        ("due_at_snapshot__isnull", False),
                        models.Q(("scheduler_version", ""), _negated=True),
                    ),
                    models.Q(
                        ("kind", "new"),
                        ("due_at_snapshot__isnull", True),
                        ("scheduler_version", ""),
                    ),
                    _connector="OR",
                ),
                name="study_session_item_kind_snapshot_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revealed_at__isnull", True),
                    models.Q(
                        ("presented_at__isnull", False),
                        ("revealed_at__gte", models.F("presented_at")),
                    ),
                    _connector="OR",
                ),
                name="study_session_item_reveal_order_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__in", ("remembered", "forgot"))),
                name="study_answer_rating_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(("accepted_at__gte", models.F("submitted_at"))),
                name="study_answer_acceptance_order_valid",
            ),
        ),
    ]
