# Generated by Django 5.2.16 on 2026-08-31 04:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import study.models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySessionWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("due", "Due review"), ("new", "New Word")],
                        max_length=8,
                    ),
                ),
                ("ready_at", models.DateTimeField()),
                ("is_in_active_window", models.BooleanField(default=False)),
                (
                    "last_presented_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="studysessionitem",
            name="study_unique_session_corpus_entry",
        ),
        migrations.AddField(
            model_name="studysession",
            name="current_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_session",
                to="study.studysessionitem",
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="day_ends_at",
            field=models.DateTimeField(default=study.models.default_study_day_end),
        ),
        migrations.AddField(
            model_name="studysession",
            name="timezone_name",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="studysessionitem",
            name="ready_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="studysessionitem",
            name="position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="studysessionword",
            name="corpus_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="study_session_words",
                to="vocabulary.corpusentry",
            ),
        ),
        migrations.AddField(
            model_name="studysessionword",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_words",
                to="study.studysession",
            ),
        ),
        migrations.AddField(
            model_name="studysessionitem",
            name="session_word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="study.studysessionword",
            ),
        ),
        migrations.AddIndex(
            model_name="studysessionitem",
            index=models.Index(
                fields=["session", "ready_at", "position"],
                name="study_session_item_ready_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studysessionword",
            index=models.Index(
                fields=["session", "cleared_at", "ready_at"],
                name="study_session_word_ready_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studysessionword",
            index=models.Index(
                fields=["session", "is_in_active_window", "ready_at"],
                name="study_session_word_window_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionword",
            constraint=models.UniqueConstraint(
                fields=("session", "corpus_entry"), name="study_unique_session_word"
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionword",
            constraint=models.UniqueConstraint(
                fields=("session", "position"),
                name="study_unique_session_word_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="studysessionword",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="study_session_word_position_positive",
            ),
        ),
    ]
