# Generated by Django 4.2.7 on 2023-12-15 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_backend', '0002_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
