# Generated by Django 5.2.16 on 2026-08-04 21:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="CorpusVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64, unique=True)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("source_digest", models.CharField(max_length=64)),
                ("corpus_digest", models.CharField(max_length=64, unique=True)),
                ("word_count", models.PositiveIntegerField()),
                ("sense_count", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-imported_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__gte", 1)),
                        name="vocabulary_corpus_schema_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("word_count__gte", 1)),
                        name="vocabulary_corpus_word_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sense_count__gte", 1)),
                        name="vocabulary_corpus_sense_count_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="vocabulary_one_active_corpus",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VocabularyWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.CharField(max_length=128)),
                ("normalized_term", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("normalized_term",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("term", ""), _negated=True),
                        name="vocabulary_word_term_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("normalized_term", ""), _negated=True),
                        name="vocabulary_word_normalized_term_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CorpusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=128)),
                ("position", models.PositiveIntegerField()),
                ("pronunciation", models.CharField(blank=True, max_length=255)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="vocabulary.corpusversion",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corpus_entries",
                        to="vocabulary.vocabularyword",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="VocabularySense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("part_of_speech", models.CharField(blank=True, max_length=32)),
                ("definition", models.TextField()),
                ("example", models.TextField()),
                ("provenance", models.JSONField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senses",
                        to="vocabulary.corpusentry",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)),
                        name="vocabulary_sense_position_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("definition", ""), _negated=True),
                        name="vocabulary_sense_definition_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("example", ""), _negated=True),
                        name="vocabulary_sense_example_not_empty",
                    ),
                    models.UniqueConstraint(
                        fields=("entry", "position"),
                        name="vocabulary_sense_unique_position",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="corpusentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("term", ""), _negated=True),
                name="vocabulary_entry_term_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="corpusentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="vocabulary_entry_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="corpusentry",
            constraint=models.UniqueConstraint(
                fields=("corpus", "word"), name="vocabulary_entry_unique_word"
            ),
        ),
        migrations.AddConstraint(
            model_name="corpusentry",
            constraint=models.UniqueConstraint(
                fields=("corpus", "position"), name="vocabulary_entry_unique_position"
            ),
        ),
    ]
