import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/navigation/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} prose prose-neutral dark:prose-invert w-full max-w-full`}
      >
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
